package com.example.pampiway.utility

val SPLASHSCREEN1 = "SplashScreen1"
val SPLASHSCREEN2 = "SplashScreen2"
val SPLASHSCREEN3 = "SplashScreen3"
val WELCOMESCREEN = "WelcomeScreen"
val SIGNINSCREEN = "SignIn"
val VERIFICATION = "Verification"
val LOCATION = "Location"
val MANUALLOCATION = "ManualLocation"
val DIALOGBOX = "DIALOG"
val SIGNUP = "Signup"
val VERIFYDETAILS = "VerifyDetails"
val home = "home"
val food = "food"
val mart = "mart"
val service = "service"
val booking = "booking"
